kind: pipeline
type: docker
name: app

steps: []
  # - name: test_backend
  #   image: python:3.7.4
  #   commands:
  #     - cd backend
  #     - pip install -r requirements.txt
  #     - pytest

---
kind: pipeline
type: ssh
name: deploy

workspace:
  base: /tmp/drone-bmedl
  path: src

server:
  host: 172.17.0.1
  user:
    from_secret: ssh_user
  password:
    from_secret: ssh_password

steps:
  - name: deploy
    environment:
      DB_USER:
        from_secret: db_user
      DB_PASSWORD:
        from_secret: db_password
      DB_ADDRESS:
        from_secret: db_address
      V20_ACCOUNT_ID:
        from_secret: v20_account_id
      V20_APPLICATION_NAME:
        from_secret: v20_application_name
      V20_TOKEN:
        from_secret: v20_token

      V20_INSTRUMENTS: EUR_USD,GBP_USD,USD_CHF,AUD_USD
    commands:
      - docker-compose down
      - docker-compose up --build -d

trigger:
  branch:
    - master

depends_on:
  - app
