version: "2.3"
services:
  backend:
    runtime: nvidia
    build:
      context: .
      dockerfile: deploy/Dockerfile.backend
    restart: unless-stopped
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_ADDRESS
    networks:
      - docker_default

  collect:
    build:
      context: .
      dockerfile: deploy/Dockerfile.collect
    restart: unless-stopped
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_ADDRESS
      - V20_ACCOUNT_ID
      - V20_APPLICATION_NAME
      - V20_TOKEN
      - V20_INSTRUMENTS
    networks:
      - docker_default

  train:
    build:
      context: .
      dockerfile: deploy/Dockerfile.neuralnet
    runtime: nvidia
    restart: unless-stopped
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_ADDRESS
      - TASKS=train
    networks:
      - docker_default

  frontend:
    build:
      context: .
      dockerfile: deploy/Dockerfile.frontend
    restart: unless-stopped
    networks:
      - docker_default

networks:
  docker_default:
    external: true
