version: "2"
services:
  backend:
    build:
      context: .
      dockerfile: deploy/Dockerfile.backend
    restart: unless-stopped
    networks: 
      - docker_default
  
  frontend:
    build:
      context: .
      dockerfile: deploy/Dockerfile.frontend
    restart: unless-stopped
    networks:
      - docker_default

networks:
  docker_default:
    external: true
