# Generated by Django 2.0.4 on 2018-04-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_GE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.TextField(max_length=50)),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('adj_price', models.FloatField()),
                ('volume_price', models.FloatField()),
                ('cahanges', models.IntegerField(max_length=3000)),
            ],
        ),
    ]
