FROM python:3
ENV PYTHONUNBUFFERED 1

RUN pip install cython
RUN pip install numpy

WORKDIR /app
COPY backend/requirements.txt /app/
RUN pip install -r requirements.txt

RUN python -m pip install --upgrade pip
RUN pip install tensorflow-gpu

COPY backend/ /app/
CMD ["python", "app/manage.py", "runserver", "0.0.0.0:80"]