FROM tensorflow/tensorflow:1.15.0-gpu-py3
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install build-essential python3-dev default-libmysqlclient-dev -y 

RUN pip install cython
RUN pip install numpy

WORKDIR /app
COPY backend/requirements.txt /app/
RUN pip install -r requirements.txt

COPY backend/ /app/
CMD ["python", "app/manage.py", "runserver", "0.0.0.0:80"]