FROM python:3
ENV PYTHONUNBUFFERED 1
WORKDIR /app
COPY backend/requirements.txt /app/
RUN pip install -r requirements.txt
COPY backend/ /app/
CMD ["python", "app/manage.py", "runserver", "0.0.0.0:80"]