FROM node:12-alpine as builder
WORKDIR /app
COPY frontend/ /app/
RUN npm install -g @angular/cli
RUN npm install

CMD ["ng", "serve", "--prod", "--optimization", "--disable-host-check", "--host", "0.0.0.0", "--port", "80"]
