FROM node:12-alpine as builder
WORKDIR /app
COPY frontend/ /app/
RUN npm install -g @angular/cli
RUN npm install
RUN ng build

FROM nginx
WORKDIR /app
COPY --from=builder /app/dist/frontend /usr/share/nginx/html