# Generated by Django 2.2.6 on 2019-10-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_USDEUR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=120)),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('bid', models.DecimalField(decimal_places=10, max_digits=15)),
                ('ask', models.DecimalField(decimal_places=10, max_digits=15)),
                ('closeoutBid', models.DecimalField(decimal_places=10, max_digits=15)),
                ('closeoutAsk', models.DecimalField(decimal_places=10, max_digits=15)),
            ],
        ),
    ]
