# Generated by Django 2.2.6 on 2019-10-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('event_date', models.DateTimeField(auto_now=True)),
                ('price_date', models.DateTimeField()),
                ('bid', models.DecimalField(decimal_places=10, max_digits=15)),
                ('liquidity', models.IntegerField()),
                ('ask', models.DecimalField(decimal_places=10, max_digits=15)),
                ('closeout_bid', models.DecimalField(decimal_places=10, max_digits=15)),
                ('closeout_ask', models.DecimalField(decimal_places=10, max_digits=15)),
                ('tradeable', models.BooleanField()),
            ],
        ),
    ]
