# Generated by Django 2.2.6 on 2019-10-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='liquidity',
            new_name='bid_liquidity',
        ),
        migrations.AddField(
            model_name='stock',
            name='ask_liquidity',
            field=models.IntegerField(default=10000000),
            preserve_default=False,
        ),
    ]
