# Generated by Django 2.2.7 on 2019-12-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20191023_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('created', models.DateTimeField(auto_now=True)),
                ('model_blob', models.BinaryField()),
            ],
        ),
    ]
