# Generated by Django 2.2.7 on 2019-12-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_networkmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='networkmodel',
            old_name='created',
            new_name='updated',
        ),
    ]
