# Generated by Django 2.2.7 on 2020-01-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_prediction_price_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('price_date', models.DateTimeField()),
                ('expected', models.IntegerField()),
                ('actual', models.IntegerField()),
            ],
        ),
    ]
