# Generated by Django 2.2.7 on 2020-01-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_backtestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestresult',
            name='name',
            field=models.CharField(default='ask', max_length=120),
            preserve_default=False,
        ),
    ]
